# Generated by Django 3.2 on 2021-04-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_alter_result_number_of_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='time_duration',
            field=models.FloatField(null=True),
        ),
    ]
